export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const CLEAR_LOGIN_PAGE = 'CLEAR_LOGIN_PAGE';
export const CLEAR_LOGIN_MESSAGE = 'CLEAR_LOGIN_MESSAGE';

